# Generated by Django 4.1 on 2022-08-12 15:14

import datetime
from django.db import migrations, models
import django.utils.timezone
import qr_gen.enums

class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Qr",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default=datetime.date(2022, 8, 12), max_length=200
                    ),
                ),
                ("qr_code", models.ImageField(blank=True, upload_to="qr_codes")),
                (
                    "qr_type",
                    models.CharField(
                        choices=[
                            (qr_gen.enums.QrType["URL"], "URL"),
                            (qr_gen.enums.QrType["WIFI"], "WIFI"),
                        ],
                        default=qr_gen.enums.QrType["URL"],
                        max_length=12,
                    ),
                ),
                ("content", models.CharField(max_length=200)),
                ("ssid", models.CharField(blank=True, default="", max_length=250)),
                (
                    "authentication",
                    models.CharField(blank=True, default="", max_length=250),
                ),
                ("password", models.CharField(blank=True, default="", max_length=400)),
                ("hidden", models.BooleanField(blank=True, default=False)),
                ("firstname", models.CharField(blank=True, max_length=200)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone", models.CharField(blank=True, max_length=100)),
                ("nickname", models.CharField(blank=True, max_length=200)),
                (
                    "birthday",
                    models.DateField(blank=True, default=django.utils.timezone.now),
                ),
                ("url", models.URLField(blank=True)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("country", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
