# Generated by Django 4.0.6 on 2022-07-30 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qr_gen', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Email',
        ),
        migrations.DeleteModel(
            name='Mecard',
        ),
        migrations.DeleteModel(
            name='SocialMedia',
        ),
        migrations.DeleteModel(
            name='Text',
        ),
        migrations.DeleteModel(
            name='WebsiteUrl',
        ),
        migrations.DeleteModel(
            name='WifiConfig',
        ),
        migrations.DeleteModel(
            name='Youtube',
        ),
    ]
