# Generated by Django 4.0.6 on 2022-08-02 19:58

import datetime
from django.db import migrations, models
import qr_gen.enums


class Migration(migrations.Migration):

    dependencies = [
        ('qr_gen', '0002_qr_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='qr',
            name='authentication',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='qr',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='qr',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='qr',
            name='password',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AddField(
            model_name='qr',
            name='qr_type',
            field=models.CharField(choices=[(qr_gen.enums.QrType['URL'], 'UrlText'), (qr_gen.enums.QrType['WIFI'], 'WIFI')], default=qr_gen.enums.QrType['URL'], max_length=10),
        ),
        migrations.AddField(
            model_name='qr',
            name='ssid',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='qr',
            name='name',
            field=models.CharField(default=datetime.date(2022, 8, 2), max_length=200),
        ),
    ]
