# Generated by Django 4.0.6 on 2022-08-02 22:42

from django.db import migrations, models
import qr_gen.enums


class Migration(migrations.Migration):

    dependencies = [
        ('qr_gen', '0003_qr_authentication_qr_created_at_qr_hidden_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qr',
            name='qr_type',
            field=models.CharField(choices=[(qr_gen.enums.QrType['URL'], 'URL'), (qr_gen.enums.QrType['WIFI'], 'WIFI')], default=qr_gen.enums.QrType['URL'], max_length=12),
        ),
    ]
