# Generated by Django 4.0.6 on 2022-08-04 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr_gen', '0006_alter_qr_birthday'),
    ]

    operations = [
        migrations.AddField(
            model_name='qr',
            name='firstname',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='qr',
            name='authentication',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='qr',
            name='hidden',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='qr',
            name='password',
            field=models.CharField(blank=True, default='', max_length=400),
        ),
        migrations.AlterField(
            model_name='qr',
            name='ssid',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
    ]
