# Generated by Django 4.0.6 on 2022-08-11 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qr_gen', '0005_alter_qr_name'),
        ('qr_gen', '0007_qr_firstname_alter_qr_authentication_alter_qr_hidden_and_more'),
    ]

    operations = [
    ]
