# Generated by Django 4.0.6 on 2022-08-01 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr_gen', '0008_coordinates_wificonfig_delete_qrgen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='generated_qr',
            field=models.ImageField(blank=True, upload_to='qr_codes'),
        ),
        migrations.AlterField(
            model_name='websiteurl',
            name='generated_qr',
            field=models.ImageField(blank=True, upload_to='qr_codes'),
        ),
    ]
