# Generated by Django 4.0.6 on 2022-08-11 11:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr_gen', '0008_merge_20220811_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qr',
            name='name',
            field=models.CharField(default=datetime.date(2022, 8, 11), max_length=200),
        ),
    ]
