# Generated by Django 4.1 on 2022-08-12 08:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qr_gen", "0009_alter_qr_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="qr",
            name="name",
            field=models.CharField(default=datetime.date(2022, 8, 12), max_length=200),
        ),
    ]
