# Generated by Django 4.0.6 on 2022-08-01 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr_gen', '0009_alter_text_generated_qr_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendemail',
            name='generated_qr',
            field=models.ImageField(blank=True, upload_to='qr_codes'),
        ),
    ]
