# Generated by Django 4.0.6 on 2022-08-01 11:01

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('qr_gen', '0010_alter_sendemail_generated_qr'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Text',
            new_name='TextAndUrl',
        ),
        migrations.DeleteModel(
            name='WebsiteUrl',
        ),
    ]
