# Generated by Django 4.0.6 on 2022-08-01 13:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr_gen', '0011_rename_text_textandurl_delete_websiteurl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mecard',
            name='org',
        ),
        migrations.AddField(
            model_name='coordinates',
            name='qr_name',
            field=models.CharField(default=datetime.date(2022, 8, 1), max_length=200),
        ),
        migrations.AddField(
            model_name='mecard',
            name='qr_name',
            field=models.CharField(default=datetime.date(2022, 8, 1), max_length=200),
        ),
        migrations.AddField(
            model_name='sendemail',
            name='qr_name',
            field=models.CharField(default=datetime.date(2022, 8, 1), max_length=200),
        ),
        migrations.AddField(
            model_name='textandurl',
            name='qr_name',
            field=models.CharField(default=datetime.date(2022, 8, 1), max_length=200),
        ),
        migrations.AddField(
            model_name='wificonfig',
            name='qr_name',
            field=models.CharField(default=datetime.date(2022, 8, 1), max_length=200),
        ),
        migrations.AlterField(
            model_name='mecard',
            name='generated_qr',
            field=models.ImageField(blank=True, upload_to='qr_codes'),
        ),
        migrations.AlterField(
            model_name='wificonfig',
            name='generated_qr',
            field=models.ImageField(blank=True, upload_to='qr_codes'),
        ),
        migrations.DeleteModel(
            name='SocialMedia',
        ),
    ]
