# Generated by Django 4.0.6 on 2022-08-01 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qr_gen', '0012_remove_mecard_org_coordinates_qr_name_mecard_qr_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coordinates',
            name='user',
        ),
        migrations.RemoveField(
            model_name='mecard',
            name='user',
        ),
        migrations.RemoveField(
            model_name='sendemail',
            name='user',
        ),
        migrations.RemoveField(
            model_name='textandurl',
            name='user',
        ),
        migrations.RemoveField(
            model_name='wificonfig',
            name='user',
        ),
    ]
